let womenData = [
    {
        "id": 1,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2076891_001_main.jpg",
        "name": "ADIDAS Girls' Fleece Hooded Pullover",
        "description":"EMS Graphic Tees are about the coolest, most comfortable, most versatile piece of clothing you'll ever own. From the trail, to the beach, to casual dinner on the patio or at your local watering hole, graphic tees look great and pair with just about any short, jean or pant you'll find in your closet.",
        "brand": "ADIDAS",
        "discount_price": 31.98,
        "original_price": 45.00,
        "type": "Long Sleeve Tee",
        "gender": "Womens",
        "size": "S",
        "color": "black"
    },
    {
        "id": 2,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2062007_314_main.jpg",
        "name": "SWD Women's Compass 4",
        "brand": "Sports Wear Delight",
        "description":"EMS Graphic Tees are about the coolest, most comfortable, most versatile piece of clothing you'll ever own. From the trail, to the beach, to casual dinner on the patio or at your local watering hole, graphic tees look great and pair with just about any short, jean or pant you'll find in your closet.",
        "discount_price": 29.98,
        "original_price": 59.99,
        "type": "Pants",
        "gender": "Womens",
        "size": "M",
        "color": "gray"
    },
    {
        "id": 3,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070716_001_main.jpg",
        "name": "SWD Women's Compass 4",
        "brand": "Sports Wear Delight",
        "description":"EMS Graphic Tees are about the coolest, most comfortable, most versatile piece of clothing you'll ever own. From the trail, to the beach, to casual dinner on the patio or at your local watering hole, graphic tees look great and pair with just about any short, jean or pant you'll find in your closet.",
        "discount_price": 29.98,
        "original_price": 59.99,
        "type": "Jackets",
        "gender": "Womens",
        "size": "L",
        "color": "ANTHRACITE"
    },
    {
        "id": 4,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070404_402_main.jpg",
        "name": "THE NORTH FACE Women's Arctic Parka",
        "brand": "THE NORTH FACE",
        "description":"EMS Graphic Tees are about the coolest, most comfortable, most versatile piece of clothing you'll ever own. From the trail, to the beach, to casual dinner on the patio or at your local watering hole, graphic tees look great and pair with just about any short, jean or pant you'll find in your closet.",
        "discount_price": 29.98,
        "original_price": 59.99,
        "type": "Jackets",
        "gender": "Womens",
        "size": "S",
        "color": "ANTHRACITE"
    },
    {
        "id": 5,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2074973_001_main.jpg",
        "name": "MOUNTAIN HARDWEAR Women's Stretchdown Jacket",
        "brand": "THE NORTH FACE",
        "description":"EMS Graphic Tees are about the coolest, most comfortable, most versatile piece of clothing you'll ever own. From the trail, to the beach, to casual dinner on the patio or at your local watering hole, graphic tees look great and pair with just about any short, jean or pant you'll find in your closet.",
        "discount_price": 29.98,
        "original_price": 59.99,
        "type": "Jackets",
        "gender": "Womens",
        "size": "M",
        "color": "black"
    },
    {
        "id":6,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070404_402_main.jpg",
        "name": "THE NORTH FACE Women's Arctic Parka",
        "brand": "THE NORTH FACE",
        "description":"EMS Graphic Tees are about the coolest, most comfortable, most versatile piece of clothing you'll ever own. From the trail, to the beach, to casual dinner on the patio or at your local watering hole, graphic tees look great and pair with just about any short, jean or pant you'll find in your closet.",
        "discount_price": 29.98,
        "original_price": 59.99,
        "type": "Jackets",
        "gender": "Womens",
        "size": "M",
        "color": "RG AVIATOR NAVY"
    },
    {
        "id":7,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2080956_001_main.jpg",
        "name": "OUTDOOR RESEARCH Women's Coldfront Down Hoodie",
        "brand": "OUTDOOR RESEARCH",
        "description":"EMS Graphic Tees are about the coolest, most comfortable, most versatile piece of clothing you'll ever own. From the trail, to the beach, to casual dinner on the patio or at your local watering hole, graphic tees look great and pair with just about any short, jean or pant you'll find in your closet.",
        "discount_price": 29.98,
        "original_price": 59.99,
        "type": "Jackets",
        "gender": "Womens",
        "size": "L",
        "color": "BLACK"
    },
    {
        "id":8,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2080956_001_main.jpg",
        "name": "OUTDOOR RESEARCH Women's Coldfront Down Hoodie",
        "brand": "OUTDOOR RESEARCH",
        "description":"EMS Graphic Tees are about the coolest, most comfortable, most versatile piece of clothing you'll ever own. From the trail, to the beach, to casual dinner on the patio or at your local watering hole, graphic tees look great and pair with just about any short, jean or pant you'll find in your closet.",
        "discount_price": 29.98,
        "original_price": 59.99,
        "type": "Jackets",
        "gender": "Womens",
        "size": "L",
        "color": "BLACK"
    },
    {
        "id":9,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070402_001_main.jpg",
        "name": "THE NORTH FACE Women’s Gotham Jacket",
        "brand": "THE NORTH FACE",
        "description":"The Women's Gotham Jacket features an updated design and body-mapped insulation to create a fitted, flattering silhouette that keeps you looking your best as you take on winter's worst.",
        "discount_price": 150.98,
        "original_price": 259.99,
        "type": "Jackets",
        "gender": "Womens",
        "size": "S",
        "color": "BLACK"
    },
    {
        "id":10,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2083214_406_main.jpg",
        "name": "THE NORTH FACE Women’s Aconcagua Hoodie Jacket",
        "brand": "THE NORTH FACE",
        "description":"The Women's Gotham Jacket features an updated design and body-mapped insulation to create a fitted, flattering silhouette that keeps you looking your best as you take on winter's worst.",
        "discount_price": 120.98,
        "original_price": 279.99,
        "type": "Jackets",
        "gender": "Womens",
        "size": "S",
        "color": "Silver"
    },
    {
        "id":11,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2083214_406_main.jpg",
        "name": "THE NORTH FACE Women’s Aconcagua Hoodie Jacket",
        "brand": "THE NORTH FACE",
        "description":"The Women's Gotham Jacket features an updated design and body-mapped insulation to create a fitted, flattering silhouette that keeps you looking your best as you take on winter's worst.",
        "discount_price": 120.98,
        "original_price": 279.99,
        "type": "Jackets",
        "gender": "Womens",
        "size": "S",
        "color": "Silver"
    },
    {
        "id":12,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2024321_205_main.jpg",
        "name": "MERRELL Women's Moab 2 Low Waterproof Hiking Shoes, Dusty Olive",
        "brand": "MERRELL",
        "description":"With a fit directly for the trails, Merrell’s low-height hiker outfits you with the basics and then some. Water-repelling attributes start at the surface and then continue inward, while stability and support, through a nylon shank, contoured footbeds, and air cushioning, begin from within to help you go forward. Along with these crucial aspects, a lugged Vibram® outsole delivers all the durability and traction needed for a dependable grip in any rough conditions you may encounter.",
        "discount_price": 67.98,
        "original_price": 202.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "Olive"
    },
    {
        "id":13,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2077730_003_main.jpg",
        "name": "KEEN Women's Targhee III Waterproof Mid Hiking Boot",
        "brand": "KEEN",
        "description":"With a fit directly for the trails, Merrell’s low-height hiker outfits you with the basics and then some. Water-repelling attributes start at the surface and then continue inward, while stability and support, through a nylon shank, contoured footbeds, and air cushioning, begin from within to help you go forward. Along with these crucial aspects, a lugged Vibram® outsole delivers all the durability and traction needed for a dependable grip in any rough conditions you may encounter.",
        "discount_price": 67.98,
        "original_price": 140.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "M",
        "color": "MAGNET ATLANTIC BL"
    },
    {
        "id":14,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2075638_001_main.jpg",
        "name": "THE NORTH FACE Women’s Sierra Mid Lace Waterproof Boots",
        "brand": "THE NORTH FACE",
        "description":"With a fit directly for the trails, Merrell’s low-height hiker outfits you with the basics and then some. Water-repelling attributes start at the surface and then continue inward, while stability and support, through a nylon shank, contoured footbeds, and air cushioning, begin from within to help you go forward. Along with these crucial aspects, a lugged Vibram® outsole delivers all the durability and traction needed for a dependable grip in any rough conditions you may encounter.",
        "discount_price": 129.98,
        "original_price": 140.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "S",
        "color": "White"
    },
    {
        "id":15,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2075560_001_main.jpg",
        "name": "THE NORTH FACE Women’s Ultra Fastpack IV FUTURELIGHT Hiking Shoe",
        "brand": "THE NORTH FACE",
        "description":"With a fit directly for the trails, Merrell’s low-height hiker outfits you with the basics and then some. Water-repelling attributes start at the surface and then continue inward, while stability and support, through a nylon shank, contoured footbeds, and air cushioning, begin from within to help you go forward. Along with these crucial aspects, a lugged Vibram® outsole delivers all the durability and traction needed for a dependable grip in any rough conditions you may encounter.",
        "discount_price": 20.98,
        "original_price": 89.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "TNFBLACK"
    },
    {
        "id":16,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2071294_001_main.jpg",
        "name": "THE NORTH FACE Women’s Ultra Fastpack IV FUTURELIGHT Hiking Shoe",
        "brand": "THE NORTH FACE",
        "description":"With a fit directly for the trails, Merrell’s low-height hiker outfits you with the basics and then some. Water-repelling attributes start at the surface and then continue inward, while stability and support, through a nylon shank, contoured footbeds, and air cushioning, begin from within to help you go forward. Along with these crucial aspects, a lugged Vibram® outsole delivers all the durability and traction needed for a dependable grip in any rough conditions you may encounter.",
        "discount_price": 20.98,
        "original_price": 89.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "M",
        "color": "TNFBLACK"
    },
    {
        "id":17,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070787_001_main.jpg",
        "name": "SOREL Women's Evie Pull-On Bootie",
        "brand": "SOREL",
        "description":"With a fit directly for the trails, Merrell’s low-height hiker outfits you with the basics and then some. Water-repelling attributes start at the surface and then continue inward, while stability and support, through a nylon shank, contoured footbeds, and air cushioning, begin from within to help you go forward. Along with these crucial aspects, a lugged Vibram® outsole delivers all the durability and traction needed for a dependable grip in any rough conditions you may encounter.",
        "discount_price": 20.98,
        "original_price": 89.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "BLACK"
    },
    {
        "id":18,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2075202_201_main.jpg",
        "name": "HI-TEC Women's Ravus Vent Mid Waterproof Hiking Boots",
        "brand": "HI-TEC",
        "description":"The Hi-Tec Ravus is a waterproof boot with a suede upper, synthetic trim and breathable mesh underlay, providing a secure and comfortable fit",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "S",
        "color": "BROWN"
    },
    {
        "id":19,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2080685_101_main.jpg",
        "name": "COLUMBIA Women's Slopeside Village Omni-Heat Mid Boots",
        "brand": "COLUMBIA",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "WHITE"
    },
    {
        "id":20,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2061585_912_main.jpg",
        "name": "SOREL Women's Tivoli IV Insulated Storm Boots",
        "brand": "SOREL",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    },
    {
        "id":21,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":22,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2077521_001_main.jpg",
        "name": "90 DEGREE BY REFLEX Women's Cire 22 Capri w/ Mesh Insert",
        "brand": "90 DEGREE BY REFLEX",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Pants",
        "gender": "Womens",
        "size": "M",
        "color": "black"
    }, 
    {
        "id":23,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Compass 4-Points Slim Pant",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "gray"
    }, 
    {
        "id":24,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2062008_314_main.jpg",
        "name": "EMS Women's Compass 4-Points Trek Pant",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 123.99,
        "type": "Pants",
        "gender": "Womens",
        "size": "S",
        "color": "GRAY"
    }, 
    {
        "id":25,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":26,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":27,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":28,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":29,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":30,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":31,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":32,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":33,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":34,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":35,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":36,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":37,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":38,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":39,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }, 
    {
        "id":40,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2070820_309_main.jpg",
        "name": "EMS Women's Squall Shell Pants",
        "brand": "Sports Wear Delight",
        "description":"These waterproof boots with an urban edge tackle winter weather in style, from cabin to city. Serious insulation and a thermal-reflective lining keep toes toasty. This sneaker-like boot combines the best of both worlds, with all-day cushioning and comfort plus tough traction on wintry surfaces.",
        "discount_price": 120.98,
        "original_price": 289.99,
        "type": "Shoes",
        "gender": "Womens",
        "size": "L",
        "color": "QUARRY"
    }
];

localStorage.setItem("womenProducts", JSON.stringify(womenData));