let kidsData = [
    {
        "id": 1,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2076891_001_main.jpg",
        "name": "Fleece Hooded Pullover",
        "brand": "ADIDAS",
        "discount_price": 31.98,
        "original_price": 45.00,
        "gender": "boys",
        "size": "L",
        "color": "black",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 2,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2074447_001_main.jpg",
        "name": "Girls Tiro Track Pants",
        "brand": "ADIDAS",
        "discount_price": 32.23,
        "original_price": 40.00,
        "gender": "girls",
        "size": "S",
        "color": "black",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 3,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2082790_405_main.jpg",
        "name": "Girls’ Reversible Mossbud Jacket",
        "brand": "THE NORTH FACE",
        "discount_price": 450.55,
        "original_price": 564.00,
        "gender": "girls",
        "size": "M",
        "color": "blue",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 4,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2073848_601_main.jpg",
        "name": "Boys' UA Short Sleeve Graphic Tee",
        "brand": "UNDER ARMOUR",
        "discount_price": 20.98,
        "original_price": 35.00,
        "gender": "boys",
        "size": "S",
        "color": "red",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 5,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2072877_601_main.jpg",
        "name": "Boys' UA Prototype 2.0 Shorts",
        "brand": "LEVI'S",
        "discount_price": 700.98,
        "original_price": 765.00,
        "gender": "girls",
        "size": "M",
        "color": "red",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 6,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2074671_404_main.jpg",
        "name": "Kids' Glacier Full Zip Hoodie",
        "brand": "THE NORTH FACE",
        "discount_price": 39.98,
        "original_price": 45.00,
        "gender": "boys",
        "size": "L",
        "color": "blue",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 7,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/1362091_001_main.jpg",
        "name": "Boys' Slim Fit Sueded Pants",
        "brand": "LEVI'S",
        "discount_price": 48.98,
        "original_price": 85.00,
        "gender": "boys",
        "size": "L",
        "color": "black",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 8,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2074514_603_main.jpg",
        "name": "Girls' UA Tech Sportstyle Short Sleeve Tee",
        "brand": "UNDER ARMOUR",
        "discount_price": 20.98,
        "original_price": 25.00,
        "gender": "girls",
        "size": "M",
        "color": "red",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 9,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2074840_602_main.jpg",
        "name": "Girls' Arctic Blast Jacket",
        "brand": "THE NORTH FACE",
        "discount_price": 59.98,
        "original_price": 80.00,
        "gender": "girls",
        "size": "S",
        "color": "red",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 10,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2082091_602_main.jpg",
        "name": "Kids' Whirlibird Cuffed Beanie",
        "brand": "COLUMBIA",
        "discount_price": 18.98,
        "original_price": 25.00,
        "gender": "kids",
        "size": "L",
        "color": "purple",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 11,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2074367_308_main.jpg",
        "name": "Boys' Camo Badge of Sport Short Sleeve Tee",
        "brand": "ADIDAS",
        "discount_price": 345.98,
        "original_price": 45.00,
        "gender": "boys",
        "size": "L",
        "color": "green",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 12,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2083887_308_main.jpg",
        "name": "Boys' Print Box Short-Sleeve Graphic Tee",
        "brand": "VANS",
        "discount_price": 20.98,
        "original_price": 33.00,
        "gender": "male",
        "size": "M",
        "color": "green",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 13,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2079893_315_main.jpg",
        "name": "Kids' Novelty Flurry Wind Hoodie",
        "brand": "THE NORTH FACE",
        "discount_price": 345.98,
        "original_price": 45.00,
        "gender": "girls",
        "size": "M",
        "color": "green",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 14,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2074671_301_main.jpg",
        "name": "Kids' Glacier Full Zip Hoodie",
        "brand": "THE NORTH FACE",
        "discount_price": 49.98,
        "original_price": 60.00,
        "gender": "female",
        "size": "S",
        "color": "green",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 15,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2079697_403_main.jpg",
        "name": "Kids' Hike Full Cushion Striped Crew Socks",
        "brand": "ADIDAS",
        "discount_price": 345.98,
        "original_price": 45.00,
        "gender": "girls",
        "size": "S",
        "color": "blue",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 16,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2048008_408_main.jpg",
        "name": "Big Boys' 502 Regular Taper Fit Jeans",
        "brand": "LEVI'S",
        "discount_price": 48.98,
        "original_price": 65.00,
        "gender": "boys",
        "size": "L",
        "color": "blue",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 17,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2075114_101_main.jpg",
        "name": "Girls' Climalite Rainbow Foil Short Sleeve Tee",
        "brand": "ADIDAS",
        "discount_price": 345.98,
        "original_price": 45.00,
        "gender": "girls",
        "size": "M",
        "color": "white",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 18,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2068890_101_main.jpg",
        "name": "8-20 3-Stripe Tricot Jacket",
        "brand": "ADIDAS",
        "discount_price": 40.98,
        "original_price": 45.00,
        "gender": "male",
        "size": "M",
        "color": "white",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 19,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2073593_601_main.jpg",
        "name": "Boys' Pre-School UA Runplay Running Shoes",
        "brand": "UNDER ARMOUR",
        "discount_price": 345.98,
        "original_price": 400.00,
        "gender": "male",
        "size": "L",
        "color": "red",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 20,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2078827_402_main.jpg",
        "name": "Boys' UA Tech 2.0 Nova Short-Sleeve Tee",
        "brand": "ADIUNDER ARMOURDAS",
        "discount_price": 22.98,
        "original_price": 45.00,
        "gender": "boys",
        "size": "L",
        "color": "blue",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 21,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2079249_460_main.jpg",
        "name": "Mission Peak Short-Sleeve Graphic Tee",
        "brand": "LEVI'S",
        "discount_price": 40.98,
        "original_price": 45.00,
        "gender": "female",
        "size": "S",
        "color": "blue",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 22,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2079249_609_main.jpg",
        "name": "Mission Peak Tee",
        "brand": "LEVI'S",
        "discount_price": 40.98,
        "original_price": 45.00,
        "gender": "female",
        "size": "M",
        "color": "purple",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 23,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2082458_601_main.jpg",
        "name": "Boys' Full Patch Short-Sleeve Tee",
        "brand": "VANS",
        "discount_price": 40.98,
        "original_price": 45.00,
        "gender": "male",
        "size": "L",
        "color": "red",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 24,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2074673_308_main.jpg",
        "name": "Suave Oso Fleece Jacket",
        "brand": "THE NORTH FACE",
        "discount_price": 345.98,
        "original_price": 490.00,
        "gender": "girls",
        "size": "S",
        "color": "green",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 25,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2065354_501_main.jpg",
        "name": "Switchback 2 Jacket",
        "brand": "COLUMBIA",
        "discount_price": 345.98,
        "original_price": 45.00,
        "gender": "girls",
        "size": "L",
        "color": "purple",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 26,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2066106_701_main.jpg",
        "name": "Thunderhead Peak Rain Jacket",
        "brand": "UNDER ARMOUR",
        "discount_price": 345.98,
        "original_price": 444.00,
        "gender": "boys",
        "size": "M",
        "color": "yellow",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 27,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2078525_402_main.jpg",
        "name": "UA Twist Polo",
        "brand": "UNDER ARMOUR",
        "discount_price": 45.98,
        "original_price": 46.00,
        "gender": "boys",
        "size": "L",
        "color": "blue",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 28,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2079771_770_main.jpg",
        "name": "Roots Studio Shirt",
        "brand": "ADIDAS",
        "discount_price": 12.98,
        "original_price": 15.00,
        "gender": "boys",
        "size": "M",
        "color": "yellow",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 29,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2066534_003_main.jpg",
        "name": "Fencemender Rebar Pant",
        "brand": "LEVI'S",
        "discount_price": 399.98,
        "original_price": 745.00,
        "gender": "girls",
        "size": "S",
        "color": "black",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 30,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2074614_405_main.jpg",
        "name": "Arroyo Flannel Shirt",
        "brand": "THE NORTH FACE",
        "discount_price": 78.98,
        "original_price": 80.00,
        "gender": "boys",
        "size": "S",
        "color": "blue",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 31,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2078577_101_main.jpg",
        "name": "Boys' Short-Sleeve Graphic Tee",
        "brand": "ADIDAS",
        "discount_price": 16.98,
        "original_price": 25.00,
        "gender": "boys",
        "size": "M",
        "color": "white",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 32,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2083886_408_main.jpg",
        "name": "VANS Boys' Print Box Short-Sleeve Graphic Tee",
        "brand": "VANS",
        "discount_price": 20.98,
        "original_price": 26.00,
        "gender": "boys",
        "size": "L",
        "color": "blue",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 33,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2079730_770_main.jpg",
        "name": "Cozy Up Short-Sleeve Tee",
        "brand": "LEVI'S",
        "discount_price": 18.98,
        "original_price": 32.00,
        "gender": "girls",
        "size": "M",
        "color": "yellow",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 34,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2043642_030_main.jpg",
        "name": "Boys' Fundamental Short-Sleeve Tee",
        "brand": "ADIDAS",
        "discount_price": 32.98,
        "original_price": 45.00,
        "gender": "boys",
        "size": "S",
        "color": "black",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 35,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2080536_404_main.jpg",
        "name": "Wicking Good Hoodie",
        "brand": "ADIDAS",
        "discount_price": 36.98,
        "original_price": 45.00,
        "gender": "girls",
        "size": "M",
        "color": "green",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 36,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2078792_404_main.jpg",
        "name": "Wander Sleeveless Tee",
        "brand": "THE NORTH FACE",
        "discount_price": 54.98,
        "original_price": 60.00,
        "gender": "boys",
        "size": "L",
        "color": "blue",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 37,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2082725_602_main.jpg",
        "name": "Half Dome Pullover Hoodie",
        "brand": "VANS ",
        "discount_price": 455.98,
        "original_price": 555.00,
        "gender": "boys",
        "size": "M",
        "color": "red",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 38,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2082725_408_main.jpg",
        "name": "Dome Pullover Hoodie",
        "brand": "COLUMBIA",
        "discount_price": 453.98,
        "original_price": 546.00,
        "gender": "boys",
        "size": "L",
        "color": "blue",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 39,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2074423_101_main.jpg",
        "name": "Girls' Fleece Joggers",
        "brand": "VANS",
        "discount_price": 32.98,
        "original_price": 45.00,
        "gender": "girls",
        "size": "M",
        "color": "white",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    },
    {
        "id": 40,
        "image": "https://res.cloudinary.com/eastern/image/upload/w_1000,q_auto,f_auto/2066114_770_main.jpg",
        "name": "Woodmont Rain Jacket",
        "brand": "THE NORTH FACE",
        "discount_price": 43.98,
        "original_price": 45.00,
        "gender": "girls",
        "size": "M",
        "color": "green",
        "description": "Made with a partially-recycled fleece that is durable and pill-resistant, the Youth Glacier Full Zip Hoodie is the bold, lightweight warmth they're searching for. Lightweight warmth Embroidered logo on left chest Three-piece hood Exposed, VISLON center front zip Welt hand pockets Durable, pill-resistant fleece Elastic binding on hood, cuffs and hem Self fabric blocking Standard fit 70D 155 G/M² 100% Recycled Polyester Fleece Pocket Lining: 75D 149 G/M² 100% Recycled Polyester Center Back: 21.75 Hood Shoulders And Sleeves: 70D 155 G/M² 100% Recycled Polyester Machine wash Imported Products on Sale are Discontinued Styles or Colors."
    }
];

localStorage.setItem("kidsProducts", JSON.stringify(kidsData));